services:
  web:
    build: .
    command:
      - gunicorn config.wsgi:application --bind 0.0.0.0:8000 --workers 2 --threads 2
    volumes:
      - static_volume: /app/static
    restart: always
    ports:
      - "8000:8000"
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 350M
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - static_volume: /app/static
      - certbot_certs:/etc/letsencrypt
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - web
    restart: always
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: 100M

  certbot:
    image: certbot/certbot
    volumes:
      - certbot_certs:/etc/letsencrypt
      - ./nginx:/etc/nginx/conf.d
      - static_volume:/app/static
    entrypoint: >
      sh -c "trap exit TERM;
             while :; do
               certbot renew --webroot -w /app/static --quiet;
               sleep 12h & wait $${!};
             done"  

volumes:
  static_volume:
  certbot_certs: