# Generated by Django 4.2.24 on 2025-10-03 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='added_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='category',
            name='updated_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='expanse',
            name='added_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='expanse',
            name='updated_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='income',
            name='added_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='income',
            name='updated_at',
            field=models.DateTimeField(),
        ),
    ]
